# Generated by Django 3.2.7 on 2021-09-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210924_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=0, unique=True),
            preserve_default=False,
        ),
    ]
